namespace HabbySdk.HabbyId
{
	public enum SdkEventName
	{
		overseas_habby_register_popup = 0,
		cancel_subscribe = 1,
		log_out = 2,
		habbyid_show = 3,
		habbyid_bt_click = 4,
		habbyid_selection_bt_click = 5,
		accountid_judge = 6,
		login_show = 7,
		register_show = 8,
		login_input_show = 9,
		unregistered_email_input_popup = 10,
		frequent_login_popup = 11,
		diff_registered_email_input_popup = 12,
		email_input_show = 13,
		privacy_agreement_check = 14,
		privacy_agreement_uncheck = 15,
		privacy_agreement_uncheck_popup = 16,
		registered_email_input_popup = 17,
		registered_email_input_toast = 18,
		login_email_input_toast = 19,
		receive_emails_check = 20,
		receive_emails_cancel = 21,
		receive_emails_cancel_popup = 22,
		verification_code_show = 23,
		verification_code_input = 24,
		cant_receive_code_click = 25,
		submit_bt_click = 26,
		verification_code_fail_popup = 27,
		habby_email_show = 28,
		refresh_bt_click = 29,
		send_bt_click = 30,
		connect_successful_show = 31,
		continue_button_show = 32,
		continue_bt_click = 33,
		close_bt_click = 34,
		email_input_click = 35,
		email_input = 36,
		popup_confirm_bt_click = 37,
		popup_back_bt_click = 38,
		email_verified = 39,
		email_failed = 40,
		cancel_bt_click = 41,
		ok_bt_click = 42
	}
}
